/* eslint-disable import/no-anonymous-default-export */
export default {
  1: {
    id: 1,
    photoUrl:
      "https://images.hindustantimes.com/tech/img/2021/02/27/960x540/untitled_image_(12)_1593162773362_1593162788344_1614408499018.jpg",
    headline: "New Google Nest Hub to feature same design, different colours",
    description:
      "Earlier this year it was reported that Google is working on a new Nest Hub with the company’s Soli radar technology that launched with the Pixel 4 in 2019. A new report now shares more details on this, and also the Nest Hub’s design.Google plans to keep the same design for its upcoming Nest Hub with a screen attached to an oblong, fabric-covered base, according to 9to5Google. The only change we’ll see is in the colour combination which will include grey, black and sand/pink, the report added. There’s also a light blue colour option planned for the Nest Hub which will most likely be similar to the Nest Audio’s ‘Sky’ colour.While the design will not change, there will be under the hood improvements in the Nest Hub. It will feature improved audio quality, and listening as well with three far-field microphones. The highlight though, will be the presence of Soli radar for gesture controls on the new Nest Hub. This technology is said to be used for sleep tracking, and it will be synced with the Google Fit app. The functionality is quite surprising and makes one wonder how exactly it will work. On the Pixel 4 and Pixel 4 XL, air gestures are used to play/pause, and swipe to skip/jump tracks. Air gestures can also be used to snooze alarms, and silence calls on the Pixel 4 phones. The Nest Hub would be the third device to use Soli radar after the Nest Thermostat. Here, it detects when the user is nearby and wakes the screen. It’s interesting to see how it will work on the Nest Hub. There’s no word on the Nest Hub’s launch yet but it’s expected to be available soon. Google is also said to price it around the same as the current Nest Hub smart display.",
  },
  2: {
    id: 2,
    photoUrl:
      "https://images.hindustantimes.com/tech/img/2021/02/27/960x540/Moto_360_1614425465941_1614425477033.JPG",
    headline: "New Moto-branded smartwatches to arrive in 2021",
    description:
      "Back in 2020, a Canadian company called eBuyNow launched the Moto 360 smartwatch as a part of its agreement with Motorola. Now, word is that the same company is expanding its agreement and launching a bunch of new Moto-branded smartwatches later this year.As per a report published investor presentation (via 9To5 Google), CE Brands Inc and eBuyNow eCommerce Ltd have entered into an amalgamation agreement, as a part of which CE Brands Inc will be assuming the operations and assets of eBuyNow eCommerce Ltd. The amalgamated company will launch a bunch of new products over the course of this year, a roadmap for which has been provided in the presentation. This roadmap reveals that three new Moto-branded smartwatches will be launched in 2021. The first one is the Moto G smartwatch, which is expected to arrive in June this year. This smartwatch has been named after the company’s G-series smartphones and it is identical to the existing Moto 360 smartwatch. The naming of the upcoming smartwatch indicates that it will be a pocket-friendly offering.",
  },
  3: {
    id: 3,
    photoUrl:
      "https://images.hindustantimes.com/tech/img/2021/02/27/960x540/2021-02-25T012714Z_4_LYNXMPEH1N1OO_RTROPTP_3_AUSTRALIA-MEDIA-FACEBOOK_1614441924774_1614442000815.JPG",
    headline:
      "Will the tech firm deal for Australia news be replicated globally?",
    description:
      "What's happened in Australia with Google and Facebook is being seen as a potential global model.  (REUTERS).Australia passed a groundbreaking law on Thursday, forcing tech giants to pay for news shared on their networks.After months of tense negotiation, the government agreed to water down elements of the new law in exchange for Facebook and Google agreeing to payment deals with struggling local media firms -- seen as a potential model for companies around the world who have seen their advertising revenues decimated by the rise of internet platforms.The British government announced a new Digital Markets Unit in November to introduce and enforce a new code to govern the behaviour of platforms that currently dominate the market, such as Google and Facebook. The unit is set to begin work in April. Though it will primarily look at tech firms' use of data for advertising, it is also charged with finding ways to support news publishers, but it is not yet clear if this will involve direct fees to tech platforms, or how news publishers will be defined.Canada appears keen to follow the Australian lead. Prime Minister Justin Trudeau discussed the issue directly with his Australian counterpart Scott Morrison by phone on Tuesday. His office said: They agreed to continue coordinating efforts to address online harm and ensure the revenues of web giants are shared more fairly with creators and media.The EU is already on the path to gaining compensation for its media companies after introducing neighbouring rights in 2019, which call for payment for showing news content in internet searches. Google strongly opposed the law, but has lately signed deals with newspapers and media groups in France to pay digital copyright payments based on viewing figures and the amount of information published.The European Commission is also on the offensive with two new directives in the works -- the Digital Services Act and Digital Markets Act -- aimed at ensuring stricter control of illegal content and creating more transparency and choice for businesses operating online.Australia's neighbour has yet to comment on the situation. But local media bosses said Wednesday that they would press the issue with the government, which is currently seeking advice on the topic.In the US, the debate on tech regulation is currently focused on the burning question of Section 230 of the Communications Decency Act 1996, which frees tech companies from any liability over inflammatory or dangerous content shared on their platforms, which President Joe Biden has expressed a desire to reform. But momentum is also growing behind a bill introduced by Democrats, the Journalism Competition and Preservation Act 2019, which would allow newspapers to form a collective bargaining group to negotiate with tech platforms.",
  },
  4: {
    id: 4,
    photoUrl:
      "https://i.guim.co.uk/img/media/d49409acd48c995bb0b767329d45923c1cd2abf2/0_89_4500_2700/master/4500.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=91e9ecb93303776399096007e240574d",
    headline: "How to avoid 'Zoom fatigue' during the Covid pandemic",
    description: `Imagine you are walking around your workplace followed incessantly by colleagues holding a mirror that causes you to stare at yourself for large parts of the day.The bizarre scenario is in effect becoming the norm in the era of physically distanced video conference meetings and this “nonverbal overload” is leading to “Zoom fatigue”, according to a study by Jeremy Bailenson, professor of communication at Stanford University.The new peer-reviewed research, published in the journal Technology, Mind and Behaviour, listed the consequences of likely unprecedentedly excessive amounts of close-up eye contact with others and reflections of oneself during prolonged video chats.“Decades of psychology research shows that when you’re looking at yourself we scrutinise ourselves, we evaluate ourselves, and this over time causes stress and negative emotions,” Bailenson told BBC Radio 4’s Today programme.
    “When we’re forced to look at ourselves in a realtime video or mirror, we do behave as an idealised version of ourselves, in other words we try to be the best person we can be. But that comes at a cost.”
    When another person’s face is extremely physically close to ours, our brains are led to believe mating or conflict is close on the horizon, according to Bailenson. “What’s happening, in effect, when you’re using Zoom for many, many hours is you’re in this hyper-aroused state.”
    But there are easy ways to avoid the intensity and minimise the inevitable lethargy, he says. These include reducing the size of the video chat window and not using full screen, and using an external keyboard to create greater distance between oneself and the grid of prying faces.
    Crucially, Zoom users can also diverge from the default settings and use the hide self-view button, or even periodically turn their camera off altogether if feasible, “to give oneself a brief nonverbal rest”, Bailenson writes.
    “This is not simply you turning off your camera to take a break from having to be nonverbally active, but also turning your body away from the screen, so that for a few minutes you are not smothered with gestures that are perceptually realistic but socially meaningless,” he says.
    In person, people can derive social cues, hints and suggestions much more easily than over video, but with mass homeworking because of Covid the frequency of video conference meetings steeply increased and Zoom became the most popular software for this purpose because it was free, effective and easy to use.
    Though the platform has become increasingly ubiquitous, as its stock value almost quadrupled, there has been little appreciation of the downsides, Bailenson suggests, as companies have sought to keep business ticking over amid vast disruption.
    The video conference epoch, in which many people remain more sedentary than if they were in the office, may also be leading to more permanent consequences.
    Virtual consultations for cosmetic procedures have risen 64% in the US since the beginning of the pandemic, according to the American Society of Plastic Surgeons.
    “We have absolutely seen an increase in the number of surgical cosmetic procedures that people have been seeking directly related to Zoom,” said Dr Michael Somenek, who has seen a 50% to 60% increase at his Washington surgery.
    “The number-one procedure that people have been coming in for is either their upper eyelids or their neck. Because they see [their neck] either hanging on the camera or looking like a double chin.”`,
  },
  5: {
    id: 5,
    photoUrl:
      "https://i.guim.co.uk/img/media/e40b6f3322e199a01dfd093b290d20cec8eaffe4/0_66_4928_2958/master/4928.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=15b113b0eedb2b5f18849d988d9ea7ae",
    headline:
      "Concerns grow as UK Covid testing labs scaled back before even opening",
    description: `New Lighthouse labs, created by the government to boost the nation’s Covid testing capacity, are to be dramatically scaled back before they open. It is understood that new multi-million pound labs in Gateshead and Plymouth, announced last year but yet to open, are among those to see a big cut in daily testing by as much as 50% compared with original plans.

    Some smaller labs will be decommissioned and others will not have their contracts renewed this spring as part of the overhaul, with officials citing new technology and the changing pressures of the pandemic as factors behind a rethink. The changes are likely to reignite the debate over the use of public money by the £22bn NHS test and trace programme.
    
    Officials insisted there would be no overall reduction in the existing capacity of more than 750,000 tests a day, and the changes would ensure better value for money. However, the move suggests capacity will not be expanded in the way originally planned. There are also there are concerns about overhauling testing capacity weeks ahead of school reopening. Dido Harding, the head of NHS Test and Trace, admitted the service had failed to predict demand when schools and universities returned last autumn.
    
    The Gateshead Lighthouse lab, scheduled to open in December, was due to have a daily capacity of 80,000 tests a day. The Plymouth lab was meant to open in January, with a 40,000-a-day capacity. Both are yet to open, but are expected to do so with significantly reduced testing targets. A so-called “mega lab” originally planned for Scotland with the capacity to process up to 300,000 tests a day has already been shelved. A similar lab in Leamington Spa is still due to go ahead as planned.
    
    Some insiders warned that the debate about testing capacity should be put on hold until after the summer, while others said that quicker and cheaper lateral flow tests, which do not need to be processed in a lab, should not be used in place of lab-based PCR tests. NHS test and trace officials said lateral flow tests were not being used this way.
    
    Gabriel Scally, visiting professor of public health at Bristol University and a member of the independent Sage group of scientists, said: “Tailoring your lab capacity to meet the need is, of course, what you should do. We’ve got to be aware that variants are coming at us – we might get a variant that damages the immunity provided by vaccination. Even if it reduced the effect of the vaccine by 50%, that would be still hugely problematic for the country. So, if they are going to reduce the labs at all, they should be mothballing them rather than bulldozing them.”
    
    The government’s focus should be on helping local public health teams to conduct rapid contact tracing and supporting and compensating people who are asked to self-isolate, according to several public health officials.
    
    Richard Murray, the chief executive of the independent charity the King’s Fund, said: “It is vital that the government gets this right – a failure to track and respond quickly to local outbreaks, especially of new variants, could mean that case numbers begin to rise, and risks squandering the hard work of the NHS and the sacrifices made by the public since the pandemic began.”
    
    Professor Maggie Rae, president of the Faculty of Public Health, said she did not want to criticise people working in the testing programme. “But what I am going to question is the amount of money spent on the programme – to what purpose and to what impact?” She asked how much of funding was also going to local authorities and their public health teams.
    
    A Department for Health and Social Care spokesperson said: “Our testing system has continued to evolve, and now includes both symptomatic tests processed in a lab, and asymptomatic tests that can be used rapidly at home or at work. Turnaround time has improved and new technology means we can process hundreds of thousands of tests a day in one lab, and respond to increased demand as needed. Our vaccine rollout also continues at pace, getting jabs into arms and offering as much protection as possible, as quickly as possible.

    “Testing must remain a vital part of the response to Covid-19 as we cautiously ease lockdown restrictions, but this improved system means we are now able to consolidate our laboratory network to achieve the best value for money. Our overall national laboratory capacity will not reduce, and everyone who needs a test will still be able to get one, quickly.”`,
  },
};
